language: generic
os: linux
dist: xenial
group: stable
sudo: required
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version
script:
  - swift test
cache:
  directories:
    - $HOME/.swiftenv