language: generic
os: linux
dist: xenial
group: stable
sudo: required
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/krazyjakee/47aeaee06bd6d3e9cdeb0506f2bf1054/raw/8dd4811dce7321bcf5032357b70184f65111a35a/swiftenv-install.sh)"
  - swift --version
script:
  - swift test
cache:
  directories:
    - $HOME/.swiftenv